//  Created by Isaque Veras on 03/15/24.
//  Copyright © 2024 Isaque Veras. All rights reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//      https://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//  limitations under the License.

package golang

import (
	"fmt"
	"os"
	"path"
	"strings"

	"github.com/isaqueveras/juaz/grammar"
	"github.com/isaqueveras/juaz/version"
)

var imports = []string{
	"context",
	"net/http",
}

func Write(juaz *grammar.Juaz) string {
	if len(juaz.Entries) == 0 {
		fmt.Fprintf(os.Stderr, "juaz: nothing to read in the file\n\nFile: %s\n", juaz.Pos.Filename)
		os.Exit(2)
	}

	if juaz.Entries[0].Package == "" {
		panic("syntax err" + juaz.Entries[0].Pos.String())
	}

	var buf strings.Builder
	buf.WriteString("// Code generated by juaz. DO NOT EDIT.\n")
	buf.WriteString("// versions: " + version.Version + "\n")
	buf.WriteString("// source: " + path.Base(juaz.Pos.Filename) + "\n\n")

	pkg := juaz.Entries[0].Package
	if pkg != "" {
		buf.WriteString("package " + pkg + "\n\n")
	}

	var importTime bool
	for _, entry := range juaz.Entries {
		if entry.Node != nil && !importTime {
			for _, field := range entry.Node.Entries {
				if field.Field.Type.Scalar != 0 && field.Field.Type.Scalar == grammar.Time {
					imports = append(imports, "time")
					importTime = true
				}
			}
		}
	}

	bufTypes := _build_type(juaz)
	bufModel := _build_model(juaz)
	bufInterfaceMethods := _build_interface_methods(juaz)
	bufStructClient := _build_struct_client(juaz)
	bufFuncNewClient := _build_func_new_client(juaz)
	bufImplementMethod := _build_implement_method(juaz)
	bufImports := _build_import()

	buf.WriteString(bufImports)
	buf.WriteString(bufTypes)
	buf.WriteString(bufModel)
	buf.WriteString(bufInterfaceMethods)
	buf.WriteString(bufStructClient)
	buf.WriteString(bufFuncNewClient)
	buf.WriteString(bufImplementMethod)

	var bufParameters string
	for _, params := range _build_parameters(juaz) {
		bufParameters += params.buf
	}

	buf.WriteString(bufParameters)

	return buf.String()
}
